micronaut:
  application:
    name: micronaut-illegal-access-error
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: NONE
    dialect: POSTGRES
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.yml'
